import oracledb

def abrirConexao(db_user, db_password, db_encoding, db_host):
    try:
        print(f"Conectando ao banco de dados: {db_host} como {db_user}")
        con = oracledb.connect(
            db_user,
            db_password,
            db_host,
            encoding=db_encoding
        )
        return con
    except oracledb.DatabaseError as e:
        error, = e.args
        print(f"Erro ao conectar no banco: (Código: {error.code} - {error.message})")
        return None

def verificar_tabelas(conn):
    """
    Verifica se a tabela principal de notícias e a tabela de log existem.
    Levanta uma exceção se não existirem, instruindo o usuário.
    """
    cur = conn.cursor()
    try:
        cur.execute("SELECT TABLE_NAME FROM USER_TABLES WHERE TABLE_NAME IN ('NOTICIAS_MUNICIPIOS', 'LOG_EXECUCAO_NOTICIAS')")
        tabelas = [row[0] for row in cur.fetchall()]
        if 'NOTICIAS_MUNICIPIOS' not in tabelas or 'LOG_EXECUCAO_NOTICIAS' not in tabelas:
            raise Exception("As tabelas necessárias para o sistema não foram encontradas no banco de dados. Por favor, execute o script com a flag --gerar-banco para criar a estrutura necessária.")
    finally:
        cur.close()

def criar_tabelas(conn):
    """
    Cria as tabelas necessárias no banco de dados, caso não existam.
    Resiliente: Não apaga nem altera estruturas alheias ou existentes de forma destrutiva.
    """
    cur = conn.cursor()
    
    # Tabela de Log
    try:
        cur.execute("""
            CREATE TABLE LOG_EXECUCAO_NOTICIAS (
                IDE_EXECUCAO NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                DES_PROCEDURE VARCHAR2(255),
                DES_ASSUNTO VARCHAR2(255),
                DAT_INICIO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                DAT_FIM TIMESTAMP,
                DES_ERRO VARCHAR2(4000),
                STATUS VARCHAR2(50) DEFAULT 'EM ANDAMENTO'
            )
        """)
        print("Tabela LOG_EXECUCAO_NOTICIAS criada com sucesso.")
    except oracledb.DatabaseError as e:
        error, = e.args
        if error.code == 955: 
            print("Tabela LOG_EXECUCAO_NOTICIAS já existe.")
        else:
            print(f"Erro ao criar tabela LOG_EXECUCAO_NOTICIAS: {error.message}")

    # Tabela de Notícias
    try:
        cur.execute("""
            CREATE TABLE NOTICIAS_MUNICIPIOS (
                IDE_NOTICIA NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                IDE_EXECUCAO NUMBER,
                TITULO VARCHAR2(1500),
                CONTEUDO CLOB,
                FONTE VARCHAR2(255),
                DAT_PUBLICACAO VARCHAR2(100),
                LINK VARCHAR2(2000),
                IMG_URL VARCHAR2(2000),
                PALAVRA_CHAVE VARCHAR2(255),
                MUNICIPIOS_CITADOS VARCHAR2(2000),
                DAT_CAPTURA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT FK_LOG_EXEC FOREIGN KEY (IDE_EXECUCAO) REFERENCES LOG_EXECUCAO_NOTICIAS(IDE_EXECUCAO)
            )
        """)
        print("Tabela NOTICIAS_MUNICIPIOS criada com sucesso.")
    except oracledb.DatabaseError as e:
        error, = e.args
        if error.code == 955:
            print("Tabela NOTICIAS_MUNICIPIOS já existe.")
        else:
            print(f"Erro ao criar tabela NOTICIAS_MUNICIPIOS: {error.message}")
            
    conn.commit()
    cur.close()

def registrar_inicio(conn, des_procedure, des_assunto):
    """
    Guarda o registro de início da execução e retorna o ID da execução.
    """
    cur = conn.cursor()
    try:
        ide_execucao = cur.var(oracledb.NUMBER)
        cur.execute("""
            INSERT INTO LOG_EXECUCAO_NOTICIAS (DES_PROCEDURE, DES_ASSUNTO) 
            VALUES (:1, :2) RETURNING IDE_EXECUCAO INTO :3
        """, (des_procedure, des_assunto, ide_execucao))
        conn.commit()
        return ide_execucao.getvalue()[0]
    except Exception as e:
        print(f"Erro ao registrar início no banco: {e}")
        return None
    finally:
        cur.close()

def registrar_fim(ide_execucao, conn):
    """
    Guarda o registro de fim da execução com status de concluído.
    """
    if not ide_execucao: return
    cur = conn.cursor()
    try:
        cur.execute("""
            UPDATE LOG_EXECUCAO_NOTICIAS 
            SET DAT_FIM = CURRENT_TIMESTAMP, STATUS = 'CONCLUIDO' 
            WHERE IDE_EXECUCAO = :1
        """, (ide_execucao,))
        conn.commit()
    except Exception as e:
        print(f"Erro ao registrar fim no banco: {e}")
    finally:
        cur.close()

def registrar_erro(ide_execucao, erro_msg, conn):
    """
    Guarda o registro de erro durante a execução.
    """
    if not ide_execucao: return
    cur = conn.cursor()
    try:
        # truncar mensagem para 4000 caracteres para evitar erro de limite de tamanho
        erro_msg_truncada = str(erro_msg)[:4000]
        cur.execute("""
            UPDATE LOG_EXECUCAO_NOTICIAS 
            SET DAT_FIM = CURRENT_TIMESTAMP, STATUS = 'ERRO', DES_ERRO = :1 
            WHERE IDE_EXECUCAO = :2
        """, (erro_msg_truncada, ide_execucao))
        conn.commit()
    except Exception as e:
        print(f"Erro ao registrar erro no banco: {e}")
    finally:
        cur.close()

def salvar_noticias(conn, df, ide_execucao):
    """
    Salva os registros formatados do dataframe na tabela de notícias.
    """
    if df is None or df.empty:
        return
    
    cur = conn.cursor()
    try:
        sql = """
            INSERT INTO NOTICIAS_MUNICIPIOS 
            (IDE_EXECUCAO, TITULO, CONTEUDO, FONTE, DAT_PUBLICACAO, LINK, IMG_URL, PALAVRA_CHAVE, MUNICIPIOS_CITADOS)
            VALUES (:1, :2, :3, :4, :5, :6, :7, :8, :9)
        """
        
        # Converte o dataframe para uma lista de tuplas
        registros = []
        for index, row in df.iterrows():
            registros.append((
                ide_execucao,
                str(row.get('titulo', ''))[:1500],
                str(row.get('conteudo', '')),
                str(row.get('fonte', ''))[:255],
                str(row.get('datetime', ''))[:100],
                str(row.get('link', ''))[:2000],
                str(row.get('img_url', ''))[:2000],
                str(row.get('palavra_chave', ''))[:255],
                str(row.get('municipios_citados', ''))[:2000]
            ))
            
        cur.executemany(sql, registros)
        conn.commit()
        print(f"✅ {len(registros)} notícias persistidas no banco de dados com sucesso.")
    except Exception as e:
        print(f"Erro ao salvar notícias no banco: {e}")
        conn.rollback()
    finally:
        cur.close()
